#!/usr/bin/env python3
"""T956 — merge the hand-audited judgement fields into records.json.

Every value below was determined by this auditor (qwen3.8-27b/T956) reading the
row's bundle, run records, findings files and git history directly.  Evidence
citations are in the *_reason fields.
"""
import json

J = {
# ── disjoint slice ───────────────────────────────────────────────────────────
"T792": ("complete",
         "brief's two halves both delivered: Half-A table (12 functions, 0 deletion candidates) + 54 unit arms on bin/subagent committed 5ca4f7c (17:06Z, before close); two real defects fixed (session-path collision, --model crash)",
         "yes",
         "pass is right: both declared deliverables in git; suite green per findings (300 arms across lanes, 0 failures); close itself was RECONSTRUCTED by T771 after the store rollback, so the verdict history is seat-recovered, not worker-written",
         "yes",
         "tests/unit/test_subagent.py + findings committed and in the suite at HEAD",
         "verified",
         "worker committed the tests itself before close (5ca4f7c); committed code is inspectable; findings record the 300-arm suite run",
         "yes",
         "operator's unit-first method applied at the launch chokepoint; two real launch-gate defects fixed in the same pass"),
"T679": ("complete",
         "tools census delivered on disk (findings/T679-tools-census.json, 42KB): per-tool KEEP/FIX verdicts incl. a confirmed live managent segfault reproduced by running the wired regression",
         "yes",
         "pass-with-findings is the honest T716 backfill close: findings existed, the row was clobbered before any committed store captured it — bundle field is empty, so declared deliverables are unknowable from the store",
         "yes",
         "T679's T27 DELETE verdict is cited in the T703 execution commit (414ace6) and the S09 module-contract spec; note the census findings file itself is still UNTRACKED in git (git status: ??)",
         "verified",
         "independent seat T703 executed the census verdicts and verified the claimlint floor; the segfault claim was made by actually running the wired regression, not asserted",
         "yes",
         "drove T703's deletions and the S09 spec; it is the fleet's tool-health census that later hygiene rows cite"),
"T618": ("complete",
         "findings file carries the exact envelope the brief requires: 19-item union + 19 adjudications with citations over the five anonymized lanes",
         "yes",
         "pass-with-findings is right: the single declared deliverable was delivered and committed (5f3c2e8/c6f278a)",
         "yes",
         "consumed by T632's grade (union_recall 22/26 recorded in tools/complementarity-inputs/race-f.json) and the complementarity record",
         "verified",
         "an independent grader (T632, non-same-family) scored the artifact against the sealed key without reading it",
         "yes",
         "Race F entrant data feeding the model-perf ledger and the S04 spec rev"),
"T803": ("complete",
         "S08 spec amendment landed at b50592f (21:42Z): §2a 'Declared resource need' + ORC-GD-1 ram_mb block, exactly the operator's 2026-08-23 ruling (task-level fit vs machine-level danger, refusal not kill)",
         "yes",
         "pass is right: both declared deliverables in git; close was RECONSTRUCTED by T771 after the store rollback (verdict history did not survive)",
         "yes",
         "spec is committed and cited by downstream rows (ram-policy.md, T806/T822 findings); the amendment text is present at HEAD",
         "verified",
         "committed spec is inspectable at HEAD and cited downstream; amendment content verified against the brief's required shape (declared need, task-level admission, refusal semantics)",
         "yes",
         "mechanizes the operator's RAM ruling as a buildable spec — admission by declared need instead of host_total//8"),
"T648": ("complete",
         "findings carry per_claim (25), lane_scores (5), complementarity and ranking (4 entries — a tied pair, per the brief's 'say tied' bar)",
         "yes",
         "pass-with-findings is right: the single declared deliverable delivered and committed e104b38",
         "yes",
         "cited in docs/infra/model-perf.md, docs/infra/races/race-corpus.md and tools/complementarity-inputs/race-g.json; grader fairness arbitrated by T649",
         "verified",
         "the grader itself was graded (T649 arbitration + complementarity inputs carry its per-claim rulings)",
         "yes",
         "the all-grade-all round that separates rubber-stamping from over-refuting in Race G — the panel data the ranking alone would discard"),
"T365": ("complete",
         "32 renames committed 048af65 (175 references / 128 files repointed, seeded control shown to fire, claimlint C2=14 before and after per findings and commit message)",
         "yes",
         "pass is right: sweep is in git and ls docs/audits/ reads chronologically at HEAD; both findings files committed (f0f5097, 748e894)",
         "yes",
         "renames are durable at HEAD; the findings files are committed and cite the sweep commit",
         "verified",
         "sweep commit 048af65 is inspectable; date-prefix state directly confirmed at HEAD; predates the run-record era so no execution record exists (recorded, not inferred)",
         "yes",
         "operator ruling executed repo-wide, including relocating the governing document DIRECTION.md to its date-prefixed path"),
"T799": ("complete",
         "fix committed 68f54e1: watch-fleet footer blanks removed, cursor hidden/restored in cleanup, plus 124 lines of new test arms in tools/regression-watch-fleet.sh (test-first per the brief)",
         "yes",
         "pass is right: deliverables in git; close RECONSTRUCTED by T771 after the store rollback",
         "yes",
         "the no-blank footer layout and cursor handling are at HEAD; arms wired into the committed regression",
         "verified",
         "fix commit 68f54e1 is inspectable and touches exactly the declared files (watcher + regression + findings)",
         "yes",
         "removes an operator-visible terminal defect (blank lines + flashing cursor) the operator had explicitly ruled on"),
"T537": ("complete",
         "AC7 windowed to 24h + verdict surfaces WARN, committed b4c5a76 (12:42Z) one minute before the 12:43Z close; findings committed 12:44Z (0d3f43e, T538 amendment to the same file)",
         "yes",
         "pass is right: the verdict logic changed so the suite cannot print ACCEPTANCE PASS over a WARN",
         "yes",
         "tools/orcha-acceptance.sh carries the fix at HEAD; later rows (T629, T872) build on the same file",
         "verified",
         "committed script is inspectable; the defect evidence (PASS printed with 22 wall-kills) is in the brief and the fix is verifiable against it",
         "yes",
         "closes 'the landmark is gateable on a lie' — the L1 bar can no longer pass while warning"),
"T573": ("complete",
         "all four brief jobs done per findings: 3x3 corrected-predicate arm (0/784), 152/784 falsification pinned as negative control, lemma text re-scoped, seeded-defect controls recorded (0->56 red, revert green); committed e16c22a before close",
         "yes",
         "pass-with-findings is accurate: the lane was wall-killed at 2700s (signal 9, exit null) AFTER it flushed its work — findings commit and close at 08:44Z, kill ~08:48Z",
         "yes",
         "the 3x3 arm + pinned 152/784 control are in src/rules.zig at HEAD, wired into zig build test",
         "verified",
         "tests are in git and the seeded-defect controls are recorded in findings (both red then green), satisfying the brief's never-trust-a-green-test bar",
         "yes",
         "the G5 green-wash — a known-falsified lemma passing silently at 2x2/3x2 — can no longer recur"),
"T582": ("complete",
         "S04 reconciler spec authored per the Phase-0 table scope (verdict+triage only, 19.4%), committed 631682b with the findings naming each satisfied ruling",
         "yes",
         "pass is right: both declared deliverables in git, committed at the run's end (12:48Z, wall 415s from 10:41Z)",
         "yes",
         "consumed by five audit lanes (incl. T618), the T632 grade, and the S06 spec; under re-audit by T963/T964",
         "verified",
         "committed spec independently audited by five non-same-family lanes; scope derived from the counted table as the brief required, not from intuition",
         "yes",
         "the sprint's centerpiece design exists, is audited, and is the input to the close-contract work in flight"),
"T506": ("complete",
         "I5 calibration delivered with denominators: 4x3 via bitset-BFS (V=1,929,035/E=6,858,926, verdict PASS) and 4x4 via WZO2 Tarjan (V=99,133,036/E=565,402,416); instrument code in src/vb_scc_4x4.zig (checkI5Wzo1Bitset), artifacts SHA-recorded",
         "yes",
         "pass-with-findings is right: the declared findings file delivered and committed 82303f1 (10:22Z, at the run's end)",
         "yes",
         "cited in ROADMAP-2026-08-20.md closing the T335/T344 4x3/4x4 calibration deferral — the last registered L2 remainder item",
         "verified",
         "instrument (checkI5Wzo1Bitset, checkI5Wzo2) is in git and re-runnable; findings report both graphs with V/E/SCC denominators, not a bare PASS",
         "yes",
         "the L2 calibration debt carried from T335/T344 is now closed at both sizes"),
"T754": ("complete",
         "Race W lane output (two drop-in sections, all cited paths checked to exist) written to the declared path and committed 2a7964d (11:55Z) a minute before close",
         "yes",
         "pass is right: the single declared deliverable is in git; the brief asked for no findings file",
         "partial",
         "T757's result: T755 won 'with three clauses grafted from T754' — the lane's text was partially absorbed into the winning terminology rewrite",
         "verified",
         "the race result (T757 findings) cites the lane output and the graft; the file is in git and inspectable",
         "yes",
         "three clauses entered the terminology rewrite that landed in GLOSSARY/DIRECTION"),
# ── control slice ────────────────────────────────────────────────────────────
"T932": ("complete",
         "round-robin partition in finishParallel + regression script committed cb5a307 (09:28Z, one minute before close); findings record the 11.5x reproduction",
         "yes",
         "pass is right: declared acceptance (sh tools/regression-finishparallel-partition.sh) exists in git and the implementation is committed",
         "yes",
         "partition code in src/retro.zig at HEAD; regression script committed",
         "verified",
         "machine acceptance declared and passing; committed regression; implements the T930 measurement (11.5x round-robin vs 5.1x contig)",
         "yes",
         "finishParallel throughput ~11.5x — one of the largest single wins on the retrograde engine this sprint"),
"T927": ("complete",
         "caffeinate guard in tools/runner + 4-arm regression (tools/regression-sleep-guard.sh) committed 41182d7 (09:11Z, before the 09:12Z close)",
         "yes",
         "pass is right: guard and regression are in git; the acceptance is declared in the bundle meta (sh tools/regression-sleep-guard.sh) though the store row records acceptance=null",
         "yes",
         "runner guard at HEAD; run records now carry sleep fields; the 2026-08-24 sleep incident (24 sleeps) was the motivating fact",
         "verified",
         "committed code + committed regression; the guard's behaviour is re-checkable by the regression's arms",
         "yes",
         "host sleep during runs made that day's wall figures suspect — the guard makes wall-clock numbers honest again"),
"T894": ("complete",
         "dispatch-readiness queue ordering (204-line main.zig change) + 304-line regression committed b27c7f0 at 09:30Z — one minute before the close but ~13 minutes after the worker's run ended (~09:17Z), i.e. committed by the T935 seat, not the worker",
         "yes",
         "pass-with-findings is an honest close: the worker exited without findings or done and the T935 seat recovered and closed it; a store-only reader sees a clean close and misses the recovery",
         "yes",
         "ordering code + regression + findings all committed in b27c7f0 and live at HEAD",
         "verified",
         "the code and regression are committed and inspectable; the commit-vs-run-time gap is the evidence of seat recovery, and the code is what it claims to be",
         "yes",
         "the dispatchable queue had sorted by task id for weeks with a malformed row pinning the head; readiness ordering fixes the queue the operator actually reads"),
"T924": ("partial",
         "the 68-minute ladder run is real (4110s headline, 7 run records) and its 'NOT tractable writes-off' verdict was confirmed by T929 — but its published solve projection was 7.585x too high (unweighted mean) and was corrected by T929; deliverables recovered from the transcript by a seat (commit 62b27bd 'recovered', 07:05Z, during the re-close attempts)",
         "yes",
         "pass-with-findings as a status label is accurate (the run completed and produced findings) — but the row's headline number was wrong until a second row re-derived it; deliverable-presence checking misses exactly this",
         "yes",
         "tractability doc + findings in git; the doc was re-pointed at T929 (2614391) after the correction, so the durable surface is now the corrected one",
         "verified",
         "T929 independently re-derived the projection from committed CSV data and confirmed the core verdict — the second row is the check that caught the 7.585x error",
         "yes",
         "measured the 4x4.D3 ladder — the #1 row by dependents (7) — and established the not-tractable-writes-off verdict T929 confirmed"),
"T921": ("none",
         "killed mid-flight during the cold-cache debug build; two run records with null wall/exit; both declared deliverables absent from disk and git",
         "yes",
         "abandoned is accurate: a true negative — nothing was produced and the close says so",
         "no",
         "nothing was written anywhere durable",
         "verified",
         "deliverable absence directly checked in git; run records show the kill; absence is recorded as observed, not inferred",
         "no",
         "no data produced; its only value is that it was closed abandoned honestly instead of passed"),
"T943": ("complete",
         "moving-parts inventory (18 items with dispositions) + regression gate committed 1d40645; the regression's false positive (harness caffeinate attributed to the project) was fixed only later by T952 (be06fdb, 35a7c40)",
         "no",
         "it closed pass via the runner's automatic close while its own declared acceptance (sh tools/regression-moving-parts.sh) was red on a clean host — a red gate recorded as a pass",
         "yes",
         "docs/infra/moving-parts.md is in git and live; the gate was repaired by T952 and is now wired into the suite",
         "self-reported",
         "the pass rests on the runner's auto-close: the only machine gate actually failed at close time; the deliverables' presence is in git but the pass itself was never established",
         "yes",
         "the inventory is exactly the operator's ask (name every moving part with a benefit) and the repaired gate now catches undocumented processes"),
"T842": ("none",
         "exit 1 at 2902s with zero deliverables (declared patch/findings absent); consumed 790 of the ~792 Ollama requests in the 5-hour window per the T771 close note — it starved its own family",
         "yes",
         "abandoned on evidence is accurate: a true negative close on a runaway model, with the cause recorded",
         "no",
         "no deliverables; the incident note on the store row is the only record",
         "verified",
         "run record (exit 1, 2902s) plus the Ollama request census recorded by the T771 seat, not the model's own report",
         "mixed",
         "no deliverable and it starved sibling lanes (T841), but the incident is what exposed the missing per-MODEL request budget — a per-FAMILY cap cannot prevent it"),
"T841": ("none",
         "exit 1 at 2909s after only 1 Ollama request — starved by T842, it barely ran; no deliverables on disk or in git",
         "yes",
         "abandoned is accurate; the close note correctly classifies it as an infra-contention datum, not a kimi capability datum",
         "no",
         "nothing was produced",
         "verified",
         "run record plus the T771 request census show it received a single request in the window",
         "no",
         "produced nothing; had it not been dispatched into the contended window the host would be no worse off"),
"T907": ("complete",
         "all 233 claim adjudications done in-tree (96 unanimous / 41 three-way split / 71 backed-vs-prose disagreements) per note and the 34KB findings; the commit was refused by the pre-commit hook tripping on an unrelated dirty file from a sibling console and was committed later by a seat at 594d860 (01:48Z, ~3.5h after the close)",
         "no",
         "blocked understates the outcome: the work was 100% complete — only the commit was blocked, and the commit later happened; the store row reads as if the work were not done",
         "yes",
         "docs/epistemic/claims-evidence-audit.md + findings in git at 594d860",
         "verified",
         "the committed artifact exists and is inspectable; five run records (one 2056s real run + four seat re-closes) match the close story",
         "yes",
         "the 233-claim evidence adjudication is central work for the epistemic register's probe-vs-prose boundary"),
"T387": ("partial",
         "the t387_budget.zig u6 bitpos<64 wrap spun the run; the DAG readings were salvaged into T397 (commit aa5f1a7 delivered the capture-budget doc + the u6 hang fix) but the Bellman-consistency reading was never taken",
         "yes",
         "blocked is honest: the acceptance (test -s docs/research/capture-budget-2026-08-06.md) only became true via T397's delivery, not this row's; predates the run-record era so no execution record exists (recorded, not inferred)",
         "partial",
         "the DAG readings + the u6 hang fix reached git via T397; the missing Bellman-consistency reading remains open",
         "verified",
         "T397's commit is inspectable — its red-then-green test caught both the hang and the rank off-by-one — and the doc is in git",
         "yes",
         "exposed the ReleaseFast u6 overflow that T397 fixed and delivered (indirectly) the capture-budget measurements"),
"T929": ("complete",
         "layer-population-weighted re-projection from committed CSV (no compute) correcting T924's 7.585x error, committed 8d5d163 'verdict confirmed'",
         "yes",
         "pass-with-findings is right: both declared deliverables in git",
         "yes",
         "projection doc + findings in git; the T924 doc was re-pointed at T929 (2614391) so the durable surface carries the corrected number",
         "verified",
         "re-derivation from committed data (no compute); the corrected number replaced the wrong one in the T924 doc — a second row checked the first",
         "yes",
         "high-utility correction: the 4x4.D3 projection the roadmap depends on is no longer 7.6x overstated"),
"T421": ("complete",
         "43 /tmp citations rescued into docs/evidence/, claimlint C10 built, and the evidence-in-git standard established — all within the 36 committed deliverables",
         "yes",
         "pass is right: no-acceptance stratum row (predates machine acceptance) but every deliverable is verifiable in git",
         "yes",
         "the evidence files, the C10 checker in src/claimlint.zig, the regression script and the AGENTS.md rule are all at HEAD and still operative",
         "verified",
         "every declared deliverable is in git and still in force (C10 runs in claimlint today); no run record exists — predates the run-record era (recorded, not inferred)",
         "yes",
         "the 'evidence in git, or the claim is not proven' rule that the whole current audit protocol rests on came from this row"),
}

path = "docs/audits/done-audit-2026-08-25/qwencloud/records.json"
recs = json.load(open(path))
by_id = {r["task_id"]: r for r in recs}
missing = set(J) - set(by_id)
assert not missing, missing
for tid, (wd, wdr, va, var_, ab, abr, sv, sver, us, usr) in J.items():
    r = by_id[tid]
    r["work_actually_done"] = wd
    r["work_actually_done_reason"] = wdr
    r["verdict_accurate"] = va
    r["verdict_accurate_reason"] = var_
    r["absorbed"] = ab
    r["absorbed_reason"] = abr
    r["self_reported_or_verified"] = sv
    r["self_reported_or_verified_reason"] = sver
    r["useful"] = us
    r["useful_reason"] = usr
with open(path, "w") as f:
    json.dump(recs, f, indent=1)
print("judgements merged for", len(J), "rows")
