#!/bin/sh
# Output version.zig content to the file specified as $1, or stdout if no arg.
set -e

cd "$(dirname "$0")/.."

commit=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
if git diff --quiet 2>/dev/null; then
    dirty="false"
else
    dirty="true"
fi
build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
zig_version=$(zig version 2>/dev/null || echo "unknown")

output() { printf '%s\n' "$1"; }

if [ $# -gt 0 ]; then
    exec > "$1"
fi

output '// generated by tools/gen-version.sh — do not edit'
output "pub const commit = \"$commit\";"
output "pub const dirty = $dirty;"
output "pub const build_date = \"$build_date\";"
output "pub const zig_version = \"$zig_version\";"
output ''
output '/// Format: "weizigo-<tool> <sha>[-dirty] built <date> zig <ver>"'
output 'pub fn banner(comptime tool: []const u8) []const u8 {'
output '    if (dirty) {'
output '        return tool ++ " " ++ commit ++ "-dirty built " ++ build_date ++ " zig " ++ zig_version;'
output '    } else {'
output '        return tool ++ " " ++ commit ++ " built " ++ build_date ++ " zig " ++ zig_version;'
output '    }'
output '}'
