#!/bin/sh
# regression-runner-harness-p95.sh — T659 controls: the shared p95 table.
#
# Operator ruling §7c.34: both fuses read one shared table
# (docs/infra/harness-p95.md), regenerated by `tools/runner
# --recompute-harness-p95`.  This regression holds the recompute to its
# contract, independent of the live (always-moving) run store:
#
#   deterministic (seeded)  recomputing a FROZEN synthetic run store twice
#                           is byte-identical, and the threshold + exclusion
#                           counts match the seeded data exactly (killed
#                           attempts and bakeoff sub-runs excluded).
#   claude-reads-table      a claude lane with --claude-liveness-timeout
#                           UNSET prints the committed table's claude
#                           threshold (T634's fuse now reads the shared
#                           table, not a hardcoded 4631 s).
#
# The synthetic run store is written under a scratch git repo in /tmp/weizigo
# — never the live repo.  The runner resolves repo_root from CWD, so the
# scratch cd IS the isolation (same convention as the sibling runner
# regressions).  MANAGENT_TASK_ID (not --task-id) avoids auto-claim/auto-done.
#
# Task: T659 · Role: worker · Model: deepseek-v4-pro · Date: 2026-08-22

set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
PROJECT="$(cd "$HERE/.." && pwd)"
RUNNER="$PROJECT/tools/runner"

mkdir -p /tmp/weizigo
WORK="$(mktemp -d /tmp/weizigo/t659-harnessp95-XXXXXX)" || { echo "regression-runner-harness-p95.sh: FATAL — scratch mktemp failed; refusing to run (T445)" >&2; exit 2; }
cd "$WORK"
git init -q

# ── live-telemetry baseline + closing isolation (T512, audit F3) ────────
LIVE_HB="$PROJECT/untracked/heartbeat.jsonl"
LIVE_HB_BASE=$(wc -l < "$LIVE_HB" 2>/dev/null || echo 0)

check_isolation() {
    ISO_FAIL=0
    APPENDED=$(tail -n +$((LIVE_HB_BASE + 1)) "$LIVE_HB" 2>/dev/null)
    if [ -z "$APPENDED" ]; then
        echo "    PASS: live heartbeat.jsonl — no lines appended during the run"
    elif echo "$APPENDED" | grep -qE 't659-harnessp95-|T9999'; then
        echo "    FAIL: fixture heartbeat line(s) appended to the LIVE heartbeat.jsonl (F3 regression)"
        echo "$APPENDED" | grep -nE 't659-harnessp95-|T9999' | sed 's/^/    | /'
        ISO_FAIL=1
    else
        echo "    PASS: live heartbeat.jsonl — appended lines carry no fixture data"
    fi
    [ "$ISO_FAIL" -eq 0 ] || exit 1
}
trap 'rm -rf "$WORK"; check_isolation' EXIT

FAIL=0

# ── a frozen synthetic run store (the recompute must be a pure function) ──
SEED="$WORK/seed"
mkdir -p "$SEED"
# Two completed pi runs (wall 100 / 200 -> p95 = 195.0, threshold = ceil(585) = 585).
printf '%s\n' '{"command": "pi --provider deepseek -p x", "exit": 0, "wall": 100.0, "task": "A1"}' > "$SEED/A1.json"
printf '%s\n' '{"command": "pi --provider deepseek -p x", "exit": 0, "wall": 200.0, "task": "A2"}' > "$SEED/A2.json"
# A killed pi attempt — must be excluded from the population.
printf '%s\n' '{"command": "pi --provider deepseek -p x", "killed": "progress timeout", "signal": 9, "wall": 1129.6, "task": "K1"}' > "$SEED/K1.json"
# A bakeoff gate sub-run — must be excluded.
printf '%s\n' '{"command": "pi --provider deepseek -p x", "exit": 0, "wall": 0.4, "task": "bakeoff"}' > "$SEED/bakeoff_b1.json"
# One completed claude and one completed ollama run.
printf '%s\n' '{"command": "claude -p x", "exit": 0, "wall": 300.0, "task": "C1"}' > "$SEED/C1.json"
printf '%s\n' '{"command": "ollama -p x", "exit": 0, "wall": 250.0, "task": "O1"}' > "$SEED/O1.json"
# An unparseable record — must be skipped, never guessed.
printf '%s\n' 'not json at all' > "$SEED/BAD.json"

echo "=== regression-runner-harness-p95: deterministic — recompute twice is byte-identical ==="
python3 "$RUNNER" --recompute-harness-p95 --runs-dir "$SEED" --harness-p95-out "$WORK/out1.md" \
    >"$WORK/out1.json" 2>"$WORK/out1.err"
python3 "$RUNNER" --recompute-harness-p95 --runs-dir "$SEED" --harness-p95-out "$WORK/out2.md" \
    >"$WORK/out2.json" 2>"$WORK/out2.err"
if diff -q "$WORK/out1.md" "$WORK/out2.md" >/dev/null 2>&1 \
   && diff -q "$WORK/out1.json" "$WORK/out2.json" >/dev/null 2>&1; then
    echo "PASS: deterministic — frozen store recomputed byte-identically (markdown + machine JSON)"
else
    echo "FAIL: deterministic — the two recomputes differ"
    diff "$WORK/out1.md" "$WORK/out2.md" | sed 's/^/    | /'
    FAIL=1
fi

echo ""
echo "=== regression-runner-harness-p95: seeded thresholds + exclusions ==="
PI_N=$(python3 -c "import json; print(json.load(open('$WORK/out1.json'))['families']['pi']['n'])")
PI_T=$(python3 -c "import json; print(json.load(open('$WORK/out1.json'))['families']['pi']['threshold_s'])")
CLAUDE_T=$(python3 -c "import json; print(json.load(open('$WORK/out1.json'))['families']['claude']['threshold_s'])")
if [ "$PI_N" = "2" ] && [ "$PI_T" = "585" ] && [ "$CLAUDE_T" = "900" ] \
   && grep -q 'killed attempts (agent lanes) | 1 |' "$WORK/out1.md" \
   && grep -q 'bakeoff gate sub-runs | 1 |' "$WORK/out1.md" \
   && grep -q 'unparseable records | 1 |' "$WORK/out1.md"; then
    echo "PASS: seeded — pi n=2 threshold=585 (killed + bakeoff excluded), claude threshold=900, exclusion counts exact"
else
    echo "FAIL: seeded — expected pi n=2 threshold=585, claude threshold=900, killed=1 bakeoff=1 unparseable=1; got pi_n=$PI_N pi_t=$PI_T claude_t=$CLAUDE_T"
    cat "$WORK/out1.json" | sed 's/^/    | /'
    FAIL=1
fi

echo ""
echo "=== regression-runner-harness-p95: claude fuse reads the shared table ==="
# The runner reads the COMMITTED table (copied into the scratch repo, which is
# its own repo_root); the claude banner must show the table's threshold, not a
# hardcoded 4631.
mkdir -p "$WORK/docs/infra" "$WORK/untracked/runs"
cp "$PROJECT/docs/infra/harness-p95.md" "$WORK/docs/infra/harness-p95.md"
cat > "$WORK/untracked/T9999-claude-fuse.md" <<'BUNDLE'
<!--managent set=A deliverables=deliverable.txt priority=99-->
# T9999 — synthetic claude-fuse fixture bundle (regression only)
BUNDLE
cat > "$WORK/claude" <<'STUB'
#!/bin/sh
echo "fast" > deliverable.txt
exit 0
STUB
chmod +x "$WORK/claude"
TABLE_CLAUDE_T=$(python3 - "$WORK/docs/infra/harness-p95.md" <<'PY'
import json, re, sys
text = open(sys.argv[1]).read()
m = re.search(r"<!-- BEGIN harness-p95 -->\s*```json\s*\n(.*?)\n```\s*\n<!-- END harness-p95 -->", text, re.DOTALL)
print(json.loads(m.group(1))["families"]["claude"]["threshold_s"])
PY
)
set +e
MANAGENT_TASK_ID=T9999 \
    "$RUNNER" --no-prepend-zig --no-host-guard --max-wall 60 -- ./claude \
    >"$WORK/claude.out" 2>"$WORK/claude.err"
CLAUDE_EXIT=$?
set -e
if [ "$CLAUDE_EXIT" -eq 0 ] && grep -q "timeout ${TABLE_CLAUDE_T}s" "$WORK/claude.err"; then
    echo "PASS: claude-reads-table — claude banner prints the shared table's threshold (${TABLE_CLAUDE_T}s), not a hardcoded value"
else
    echo "FAIL: claude-reads-table — expected banner 'timeout ${TABLE_CLAUDE_T}s', got exit $CLAUDE_EXIT"
    cat "$WORK/claude.err" | sed 's/^/    | /'
    FAIL=1
fi

echo ""
if [ "$FAIL" -eq 0 ]; then
    echo "=== regression-runner-harness-p95: ALL CONTROLS PASSED ==="
    exit 0
else
    echo "=== regression-runner-harness-p95: FAILURES ==="
    exit 1
fi
