////////////////////////////////////////////
//                                        //
//    (c) 2026 Alexander E Genaud         //
//                                        //
//    Permission is granted hereby,       //
//    to copy, share, use, modify,        //
//        for purposes any,               //
//        for free or for money,          //
//    provided these notices multiply.    //
//                                        //
//    This work "as is" I provide,        //
//    no warranty express or implied,     //
//        for, no purpose fit,            //
//        'tis unmerchantable shit.       //
//    Liability for damages denied.       //
//                                        //
////////////////////////////////////////////
//
// SMD1 — solver-side move-set dump utility (T341, G3b pass0, plan §2.5/§5).
//
// Emits the SMD1 binary format defined in
//   docs/epic-01-markovian/sprints/verify-battery/pass0/design-M1.md §4.6
// (the authoritative contract: 28-byte header, sorted records, CRC-32
// ISO-HDLC, bit-per-cell move bitmap + pass bit, slice ko=NONE passes=0).
//
// The legal-move set in every record is generated by the KERNEL move
// generator (src/rules.zig, T339/MG-KERN) — NOT the solver's. This is the
// whole point of I11: the battery's independently-authored R8 move generator
// (src/vb_movegen.zig, T340) is compared, via SMD1, against the kernel. Using
// the solver's move generator here would defeat the independence (brief
// "Wrong answer" foreclosure #2).
//
// Slice. Every record is at the artifact slot: ko = NONE, passes = 0. The
// header records slice_ko = 255 (the SMD1 NONE sentinel — a format constant,
// distinct from the kernel's `ko >= n` convention) and slice_passes = 0.
// Move generation passes the kernel's ko_none (= n) so no point is ko-forbidden.
//
// Scope (plan §2.5/§3):
//   • 2x2, 3x2, 3x3 — EXHAUSTIVE: every legal position, both sides, in colex
//     order (records are sorted by (colex, side) by construction).
//   • 4x4 — SAMPLED: 50 000 states, stratified 25k Black / 25k White across
//     10 colex-decile strata (5 000 per stratum = 2 500 per stratum-side),
//     seed 31337. A `.smd1.json` sidecar records the seed, strata counts and
//     (when --artifact is given) the artifact SHA-256 for provenance.
//
// Module imports. This file is wired into the build graph by build.zig (the
// sprint console owns build.zig). The single named module "engine" is provided
// either by build.zig (addImport, rooted at src/smd1_engine.zig) or, for
// standalone `zig run`/`zig test` before wiring, by a -M flag:
//
//   @import("engine") -> src/smd1_engine.zig (re-exports rules, colex, enumerate)
//
// Standalone run (before build.zig wiring):
//   tools/runner -- zig run --dep engine -Mmain=tools/smd1.zig \
//       -Mengine=src/smd1_engine.zig -- <goban> <out.smd1> [--seed S]
//       [--sample N] [--artifact path]
//
// Standalone tests:
//   zig test --dep engine -Mmain=tools/smd1.zig -Mengine=src/smd1_engine.zig
//
// stdout = data (one summary line per dump: goban, mode, record_count, path),
// stderr = diagnostics (per util.note convention). Reference: src/util.zig.

const std = @import("std");
// The kernel move generator (rules), the colex indexer (colex) and the
// legal-position enumerator (enumerate) all live under src/ and are reached
// through the single "engine" re-export shim (src/smd1_engine.zig). Zig 0.16
// forbids a file in two modules, and rules.zig transitively imports
// colex.zig/enumerate.zig, so they cannot be separate module roots; the shim
// is the one module root that owns all three. See src/smd1_engine.zig.
const engine = @import("engine");
const rules = engine.rules;
const colex = engine.colex;
const enumerate = engine.enumerate;

// ── SMD1 format constants (design-M1 §4.6) ────────────────────────────────

const MAGIC = [_]u8{ 'S', 'M', 'D', '1' };
const VERSION: u8 = 1;
const HEADER_LEN: usize = 28;
/// SMD1 header sentinel for "no ko point at this slice". This is a FORMAT
/// constant (always 255 in the header), distinct from the kernel's runtime
/// `ko >= n` convention — the kernel's ko_none(= n) is what move generation
/// receives; 255 is what the header records.
const SLICE_KO_NONE: u8 = 255;
const SLICE_PASSES: u8 = 0;

const ValidateError = error{
    BadMagic,
    BadVersion,
    BadGoban,
    BadSlice,
    BadCrc,
    Truncated,
};

/// Monotonic milliseconds (std.time.milliTimestamp is gone in Zig 0.16).
fn nowMs() u64 {
    var ts: std.c.timespec = undefined;
    _ = std.c.clock_gettime(.MONOTONIC, &ts);
    return @as(u64, @intCast(ts.sec)) * 1000 + @as(u64, @intCast(ts.nsec)) / 1_000_000;
}

/// Bytes per colex index (design-M1 §4.6.2): 1 when 3^(w*h) ≤ 255; 4 up to
/// 4×3; 8 for 4×4. The supported gobans are 2×2, 3×2, 3×3, 4×3, 4×4.
fn colexBytes(n: usize) u8 {
    if (n <= 4) return 1; // 2x2: 3^4 = 81 ≤ 255
    if (n <= 12) return 4; // 3x2, 3x3, 4x3: up to 3^12 fits u32
    return 8; // 4x4 (spec mandates 8 even though 4 would suffice)
}

/// Write the low `nbytes` little-endian bytes of `val` into buf at `off`.
fn writeColexLE(buf: []u8, off: usize, val: u64, nbytes: u8) void {
    var i: usize = 0;
    while (i < nbytes) : (i += 1) {
        buf[off + i] = @intCast((val >> @intCast(i * 8)) & 0xFF);
    }
}

/// Append one SMD1 record (colex_idx | side | move_bitmap) to `buf`.
/// side_byte: 1 = Black to move, 2 = White to move (design-M1 §4.6.3).
fn appendRecord(
    buf: *std.ArrayListUnmanaged(u8),
    gpa: std.mem.Allocator,
    colex_idx: u64,
    side_byte: u8,
    bitmap: []const u8,
    cb: u8,
) !void {
    var rec: [12]u8 = undefined; // max = colex_bytes(8) + 1 + moves_bytes(3)
    const cbu: usize = cb;
    writeColexLE(&rec, 0, colex_idx, cb);
    rec[cbu] = side_byte;
    @memcpy(rec[cbu + 1 ..][0..bitmap.len], bitmap);
    try buf.appendSlice(gpa, rec[0 .. cbu + 1 + bitmap.len]);
}

/// Assemble the full SMD1 file: 28-byte header + records + trailing CRC-32.
/// The header's payload_crc32 field and the trailing 4-byte CRC are the same
/// value (CRC-32 ISO-HDLC of the records only — not the header).
fn assembleFile(
    gpa: std.mem.Allocator,
    w: usize,
    h: usize,
    cb: u8,
    mb: usize,
    record_count: u32,
    record_bytes: []const u8,
) ![]u8 {
    const total_len = HEADER_LEN + record_bytes.len + 4;
    const out = try gpa.alloc(u8, total_len);
    @memcpy(out[0..4], &MAGIC);
    out[4] = VERSION;
    out[5] = @intCast(w);
    out[6] = @intCast(h);
    out[7] = cb;
    out[8] = @intCast(mb);
    out[9] = 0;
    out[10] = 0;
    out[11] = 0; // reserved
    std.mem.writeInt(u32, out[12..16], record_count, .little);
    out[16] = SLICE_KO_NONE;
    out[17] = 0;
    out[18] = 0;
    out[19] = 0;
    out[20] = SLICE_PASSES;
    out[21] = 0;
    out[22] = 0;
    out[23] = 0;
    var crc = std.hash.crc.Crc32IsoHdlc.init();
    crc.update(record_bytes);
    const crc_val = crc.final();
    std.mem.writeInt(u32, out[24..28], crc_val, .little);
    @memcpy(out[HEADER_LEN..][0..record_bytes.len], record_bytes);
    std.mem.writeInt(u32, out[HEADER_LEN + record_bytes.len ..][0..4], crc_val, .little);
    return out;
}

/// Validate an SMD1 file: magic, version, goban, slice, length, and CRC-32
/// (both the header field and the trailing copy must match the recomputed
/// CRC of the records). Returns the parsed header fields on success.
fn validate(bytes: []const u8, w: usize, h: usize) ValidateError!struct {
    record_count: u32,
    cb: u8,
    mb: u8,
} {
    if (bytes.len < HEADER_LEN) return error.Truncated;
    if (!std.mem.eql(u8, bytes[0..4], &MAGIC)) return error.BadMagic;
    if (bytes[4] != VERSION) return error.BadVersion;
    if (bytes[5] != w or bytes[6] != h) return error.BadGoban;
    const cb = bytes[7];
    const mb: usize = bytes[8];
    if (bytes[9] != 0 or bytes[10] != 0 or bytes[11] != 0) return error.Truncated;
    const record_count = std.mem.readInt(u32, bytes[12..16], .little);
    if (bytes[16] != SLICE_KO_NONE or bytes[17] != 0 or bytes[18] != 0 or bytes[19] != 0)
        return error.BadSlice;
    if (bytes[20] != SLICE_PASSES or bytes[21] != 0 or bytes[22] != 0 or bytes[23] != 0)
        return error.BadSlice;
    const stored_crc = std.mem.readInt(u32, bytes[24..28], .little);
    const rec_len: usize = @as(usize, record_count) * (@as(usize, cb) + 1 + mb);
    if (bytes.len != HEADER_LEN + rec_len + 4) return error.Truncated;
    const record_bytes = bytes[HEADER_LEN..][0..rec_len];
    var crc = std.hash.crc.Crc32IsoHdlc.init();
    crc.update(record_bytes);
    if (crc.final() != stored_crc) return error.BadCrc;
    const trailing = std.mem.readInt(u32, bytes[HEADER_LEN + rec_len ..][0..4], .little);
    if (trailing != stored_crc) return error.BadCrc;
    return .{ .record_count = record_count, .cb = cb, .mb = @intCast(mb) };
}

const ExhaustiveResult = struct {
    file: []u8,
    record_count: u32,
    legal_count: u32,
};

/// Exhaustive dump for goban w×h: every legal position, both sides, at the
/// artifact slice (ko=NONE, passes=0). Records are emitted in colex-ascending
/// order with Black (1) before White (2) per position — i.e. already sorted
/// by (colex, side), so no explicit sort is needed.
fn emitExhaustive(comptime w: usize, comptime h: usize, gpa: std.mem.Allocator) !ExhaustiveResult {
    const R = rules.Rules(w, h);
    const X = colex.Indexer(w, h);
    const E = enumerate.Enumerator(w, h);
    const n = w * h;
    const cb = colexBytes(n);
    const mb = R.moves_bytes;
    const ko_none = R.ko_none();

    var records: std.ArrayListUnmanaged(u8) = .empty;
    defer records.deinit(gpa);

    var legal_count: u32 = 0;
    var idx: u64 = 0;
    while (idx < X.total) : (idx += 1) {
        const pos = X.pos_from_colex(idx);
        if (!E.is_legal(&pos)) continue;
        legal_count += 1;
        const bm_b = R.legalMoves(&pos, 1, ko_none, 0);
        try appendRecord(&records, gpa, idx, 1, bm_b[0..], cb);
        const bm_w = R.legalMoves(&pos, -1, ko_none, 0);
        try appendRecord(&records, gpa, idx, 2, bm_w[0..], cb);
    }
    const rec_size: usize = @as(usize, cb) + 1 + mb;
    const record_count: u32 = @intCast(records.items.len / rec_size);
    const file = try assembleFile(gpa, w, h, cb, mb, record_count, records.items);
    return .{ .file = file, .record_count = record_count, .legal_count = legal_count };
}

const StratumCount = struct {
    decile: usize,
    colex_lo: u64,
    colex_hi: u64,
    black: u32,
    white: u32,
};

const SampledResult = struct {
    file: []u8,
    sidecar: []u8,
    record_count: u32,
    strata: [10]StratumCount,
    legal_sampled: u32,
};

/// Stratified random sample for goban w×h (plan §3): `n_total` states split
/// across 10 colex-decile strata × 2 sides. Each stratum contributes
/// `n_total / 10` states = `n_total / 20` per stratum-side. `n_total` must be
/// a positive multiple of 20. Positions are rejection-sampled from the legal
/// positions whose colex falls in the stratum's decile range; a per-stratum-
/// side dedup set guarantees no duplicate (colex, side) record. Records are
/// sorted by (colex, side) before assembly.
fn emitSampled(
    comptime w: usize,
    comptime h: usize,
    gpa: std.mem.Allocator,
    seed: u64,
    n_total: u32,
    artifact_path: ?[]const u8,
    artifact_sha: ?[32]u8,
) !SampledResult {
    const R = rules.Rules(w, h);
    const X = colex.Indexer(w, h);
    const E = enumerate.Enumerator(w, h);
    const n = w * h;
    const cb = colexBytes(n);
    const mb = R.moves_bytes;
    const ko_none = R.ko_none();

    if (n_total == 0 or n_total % 20 != 0) return error.InvalidSampleSize;
    const n_per_stratum_side: u32 = n_total / 20;

    const Rec = struct { colex: u64, side: u8, bm: [mb]u8 };
    var recs: std.ArrayListUnmanaged(Rec) = .empty;
    defer recs.deinit(gpa);
    try recs.ensureTotalCapacity(gpa, n_total);

    var prng = std.Random.DefaultPrng.init(seed);
    const rnd = prng.random();

    var seen = std.AutoHashMap(u64, void).init(gpa);
    defer seen.deinit();

    var strata: [10]StratumCount = undefined;
    const total = X.total;
    const decile_width: u64 = total / 10;
    var legal_sampled: u32 = 0;

    for (0..10) |d| {
        const lo: u64 = @as(u64, d) * decile_width;
        const hi: u64 = if (d == 9) total else lo + decile_width;
        strata[d] = .{ .decile = d, .colex_lo = lo, .colex_hi = hi, .black = 0, .white = 0 };
        // Each side independently.
        inline for (.{ @as(i8, 1), @as(i8, -1) }) |side| {
            seen.clearRetainingCapacity();
            const side_byte: u8 = if (side > 0) 1 else 2;
            var got: u32 = 0;
            // Rejection-sample legal, not-yet-seen positions in [lo, hi).
            while (got < n_per_stratum_side) {
                const r = rnd.intRangeAtMost(u64, lo, hi - 1);
                const pos = X.pos_from_colex(r);
                if (!E.is_legal(&pos)) continue;
                if (seen.contains(r)) continue;
                try seen.put(r, {});
                const bm = R.legalMoves(&pos, side, ko_none, 0);
                try recs.append(gpa, .{ .colex = r, .side = side_byte, .bm = bm });
                got += 1;
                legal_sampled += 1;
            }
            if (side > 0) strata[d].black = got else strata[d].white = got;
        }
    }

    // Sort by (colex, side) ascending (design-M1 §4.6.1).
    std.mem.sort(Rec, recs.items, {}, struct {
        fn lt(_: void, a: Rec, b: Rec) bool {
            if (a.colex != b.colex) return a.colex < b.colex;
            return a.side < b.side;
        }
    }.lt);

    var records: std.ArrayListUnmanaged(u8) = .empty;
    defer records.deinit(gpa);
    for (recs.items) |r| {
        try appendRecord(&records, gpa, r.colex, r.side, r.bm[0..], cb);
    }
    const record_count: u32 = @intCast(recs.items.len);
    const file = try assembleFile(gpa, w, h, cb, mb, record_count, records.items);
    const sidecar = try buildSidecar(
        gpa,
        w,
        h,
        cb,
        mb,
        record_count,
        seed,
        n_total,
        n_per_stratum_side,
        &strata,
        artifact_path,
        artifact_sha,
    );
    return .{
        .file = file,
        .sidecar = sidecar,
        .record_count = record_count,
        .strata = strata,
        .legal_sampled = legal_sampled,
    };
}

fn hexSha256(hash: [32]u8) [64]u8 {
    const hex = "0123456789abcdef";
    var buf: [64]u8 = undefined;
    for (0..32) |i| {
        buf[i * 2] = hex[hash[i] >> 4];
        buf[i * 2 + 1] = hex[hash[i] & 0xF];
    }
    return buf;
}

/// Append a formatted string to `buf`, freeing the temporary allocPrint slice.
fn appendF(
    buf: *std.ArrayListUnmanaged(u8),
    gpa: std.mem.Allocator,
    comptime fmt: []const u8,
    args: anytype,
) !void {
    const s = try std.fmt.allocPrint(gpa, fmt, args);
    defer gpa.free(s);
    try buf.appendSlice(gpa, s);
}

/// Build the `.smd1.json` sidecar (design-M1 §4.6.7). For sampled dumps it
/// records the seed and per-stratum counts (brief acceptance #4); for
/// exhaustive dumps it records the mode and counts. The artifact SHA-256 is
/// included when supplied (--artifact) for provenance.
fn buildSidecar(
    gpa: std.mem.Allocator,
    w: usize,
    h: usize,
    cb: u8,
    mb: usize,
    record_count: u32,
    seed: u64,
    n_total: u32,
    n_per_stratum_side: u32,
    strata: *const [10]StratumCount,
    artifact_path: ?[]const u8,
    artifact_sha: ?[32]u8,
) ![]u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    defer buf.deinit(gpa);
    try appendF(&buf, gpa, "{{\n", .{});
    try appendF(&buf, gpa, "  \"format\": \"SMD1\",\n", .{});
    try appendF(&buf, gpa, "  \"version\": {d},\n", .{VERSION});
    try appendF(&buf, gpa, "  \"goban\": \"{d}x{d}\",\n", .{ w, h });
    try appendF(&buf, gpa, "  \"w\": {d},\n  \"h\": {d},\n", .{ w, h });
    try appendF(&buf, gpa, "  \"mode\": \"sampled\",\n", .{});
    try appendF(&buf, gpa, "  \"record_count\": {d},\n", .{record_count});
    try appendF(&buf, gpa, "  \"colex_bytes\": {d},\n", .{cb});
    try appendF(&buf, gpa, "  \"moves_bytes\": {d},\n", .{mb});
    try appendF(&buf, gpa, "  \"slice_ko\": {d},\n", .{SLICE_KO_NONE});
    try appendF(&buf, gpa, "  \"slice_passes\": {d},\n", .{SLICE_PASSES});
    try appendF(&buf, gpa, "  \"slice\": \"ko=NONE, passes=0\",\n", .{});
    try appendF(&buf, gpa, "  \"seed\": {d},\n", .{seed});
    try appendF(&buf, gpa, "  \"sample_size\": {d},\n", .{n_total});
    try appendF(&buf, gpa, "  \"n_per_stratum_side\": {d},\n", .{n_per_stratum_side});
    try appendF(&buf, gpa, "  \"sampling_frame\": \"legal positions (OEIS A094777 for square gobans; {d}x{d} rectangular)\",\n", .{ w, h });
    try appendF(&buf, gpa, "  \"generator\": \"kernel (src/rules.zig, T339/MG-KERN)\",\n", .{});
    try appendF(&buf, gpa, "  \"strata\": [\n", .{});
    for (strata, 0..) |s, i| {
        try appendF(&buf, gpa, "    {{\"decile\": {d}, \"colex_lo\": {d}, \"colex_hi\": {d}, \"black\": {d}, \"white\": {d}}}{s}\n", .{
            s.decile, s.colex_lo, s.colex_hi, s.black, s.white, if (i + 1 < 10) "," else "",
        });
    }
    try appendF(&buf, gpa, "  ],\n", .{});
    if (artifact_path) |p| {
        try appendF(&buf, gpa, "  \"artifact_path\": \"{s}\",\n", .{p});
        if (artifact_sha) |sha| {
            try appendF(&buf, gpa, "  \"artifact_sha256\": \"{s}\"\n", .{hexSha256(sha)});
        } else {
            try appendF(&buf, gpa, "  \"artifact_sha256\": null\n", .{});
        }
    } else {
        try appendF(&buf, gpa, "  \"artifact_path\": null,\n", .{});
        try appendF(&buf, gpa, "  \"artifact_sha256\": null\n", .{});
    }
    try appendF(&buf, gpa, "}}\n", .{});
    return try buf.toOwnedSlice(gpa);
}

/// Build the exhaustive sidecar (no seed/strata).
fn buildExhaustiveSidecar(
    gpa: std.mem.Allocator,
    w: usize,
    h: usize,
    cb: u8,
    mb: usize,
    record_count: u32,
    legal_count: u32,
    artifact_path: ?[]const u8,
    artifact_sha: ?[32]u8,
) ![]u8 {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    defer buf.deinit(gpa);
    try appendF(&buf, gpa, "{{\n", .{});
    try appendF(&buf, gpa, "  \"format\": \"SMD1\",\n", .{});
    try appendF(&buf, gpa, "  \"version\": {d},\n", .{VERSION});
    try appendF(&buf, gpa, "  \"goban\": \"{d}x{d}\",\n", .{ w, h });
    try appendF(&buf, gpa, "  \"w\": {d},\n  \"h\": {d},\n", .{ w, h });
    try appendF(&buf, gpa, "  \"mode\": \"exhaustive\",\n", .{});
    try appendF(&buf, gpa, "  \"record_count\": {d},\n", .{record_count});
    try appendF(&buf, gpa, "  \"legal_positions\": {d},\n", .{legal_count});
    try appendF(&buf, gpa, "  \"colex_bytes\": {d},\n", .{cb});
    try appendF(&buf, gpa, "  \"moves_bytes\": {d},\n", .{mb});
    try appendF(&buf, gpa, "  \"slice_ko\": {d},\n", .{SLICE_KO_NONE});
    try appendF(&buf, gpa, "  \"slice_passes\": {d},\n", .{SLICE_PASSES});
    try appendF(&buf, gpa, "  \"slice\": \"ko=NONE, passes=0\",\n", .{});
    try appendF(&buf, gpa, "  \"sampling_frame\": \"all legal positions, both sides\",\n", .{});
    try appendF(&buf, gpa, "  \"generator\": \"kernel (src/rules.zig, T339/MG-KERN)\",\n", .{});
    if (artifact_path) |p| {
        try appendF(&buf, gpa, "  \"artifact_path\": \"{s}\",\n", .{p});
        if (artifact_sha) |sha| {
            try appendF(&buf, gpa, "  \"artifact_sha256\": \"{s}\"\n", .{hexSha256(sha)});
        } else {
            try appendF(&buf, gpa, "  \"artifact_sha256\": null\n", .{});
        }
    } else {
        try appendF(&buf, gpa, "  \"artifact_path\": null,\n", .{});
        try appendF(&buf, gpa, "  \"artifact_sha256\": null\n", .{});
    }
    try appendF(&buf, gpa, "}}\n", .{});
    return try buf.toOwnedSlice(gpa);
}

// ── CLI ────────────────────────────────────────────────────────────────────

const Cli = struct {
    goban: []const u8,
    out_path: []const u8,
    seed: u64 = 31337,
    sample: ?u32 = null,
    artifact: ?[]const u8 = null,
};

fn parseArgsDump(goban_opt: ?[]const u8, iter: *std.process.Args.Iterator) !Cli {
    const goban = goban_opt orelse return error.MissingGoban;
    const out_path = iter.next() orelse return error.MissingOutPath;
    var cli = Cli{ .goban = goban, .out_path = out_path };
    while (iter.next()) |arg| {
        if (std.mem.eql(u8, arg, "--seed")) {
            const v = iter.next() orelse return error.MissingValue;
            cli.seed = std.fmt.parseUnsigned(u64, v, 10) catch return error.BadValue;
        } else if (std.mem.eql(u8, arg, "--sample")) {
            const v = iter.next() orelse return error.MissingValue;
            cli.sample = std.fmt.parseUnsigned(u32, v, 10) catch return error.BadValue;
        } else if (std.mem.eql(u8, arg, "--artifact")) {
            const v = iter.next() orelse return error.MissingValue;
            cli.artifact = v;
        } else {
            return error.UnknownArg;
        }
    }
    return cli;
}

fn usageMsg() void {
    std.debug.print(
        \\usage: smd1 <goban> <out.smd1> [--seed S] [--sample N] [--artifact path]
        \\       smd1 verify <in.smd1> <goban>
        \\  goban: 2x2 | 3x2 | 3x3 | 4x4
        \\  2x2/3x2/3x3 -> exhaustive (every legal position, both sides).
        \\  4x4        -> sampled (default N=50000, seed=31337; 10 colex-decile
        \\                strata x 2 sides, 2500 per stratum-side).
        \\  --sample N : override the 4x4 sample size (must be a multiple of 20).
        \\  --artifact P: record SHA-256 of the WZO2 artifact in the sidecar.
        \\  verify    : load <in.smd1> and validate magic/version/goban/slice/CRC.
        \\
    , .{});
}

/// Parse "WxH" into (w, h). Returns null on malformed input.
fn parseGoban(s: []const u8) ?struct { w: usize, h: usize } {
    const x = std.mem.indexOfScalar(u8, s, 'x') orelse return null;
    const w = std.fmt.parseUnsigned(usize, s[0..x], 10) catch return null;
    const h = std.fmt.parseUnsigned(usize, s[x + 1 ..], 10) catch return null;
    if (w == 0 or h == 0) return null;
    return .{ .w = w, .h = h };
}

/// Compute the SHA-256 of a file. Reads the whole file (the 4x4 artifact is
/// 518 MB, well under the 4 GB runner cap) and hashes it — the same path
/// oracle_v2_accept uses to load the artifact. Returns null on failure so the
/// sidecar degrades gracefully (records null) instead of aborting the dump.
fn sha256File(io: std.Io, path: []const u8, gpa: std.mem.Allocator) ![32]u8 {
    const dir = std.Io.Dir.cwd();
    const bytes = dir.readFileAlloc(io, path, gpa, .unlimited) catch return error.OpenFailed;
    defer gpa.free(bytes);
    var digest: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(bytes, &digest, .{});
    return digest;
}

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const gpa = std.heap.page_allocator;

    var args_iter = std.process.Args.Iterator.init(init.minimal.args);
    const first = args_iter.next();
    _ = first; // binary name
    const sub = args_iter.next();

    // `smd1 verify <in.smd1> <goban>` — load + validate (acceptance #5).
    if (sub != null and std.mem.eql(u8, sub.?, "verify")) {
        const in_path = args_iter.next() orelse {
            usageMsg();
            std.debug.print("error: verify needs <in.smd1> <goban>\n", .{});
            std.process.exit(2);
        };
        const gstr = args_iter.next() orelse {
            usageMsg();
            std.debug.print("error: verify needs <in.smd1> <goban>\n", .{});
            std.process.exit(2);
        };
        const dims = parseGoban(gstr) orelse {
            usageMsg();
            std.debug.print("error: bad goban '{s}'\n", .{gstr});
            std.process.exit(2);
        };
        return runVerify(io, gpa, in_path, dims.w, dims.h);
    }

    // Default dump mode: <goban> <out.smd1> [opts]. Re-parse with the goban first.
    const cli = parseArgsDump(sub, &args_iter) catch |e| {
        usageMsg();
        std.debug.print("error: {s}\n", .{@errorName(e)});
        std.process.exit(2);
    };

    const dims = parseGoban(cli.goban) orelse {
        usageMsg();
        std.debug.print("error: bad goban '{s}'\n", .{cli.goban});
        std.process.exit(2);
    };

    // Artifact SHA-256 for the sidecar (optional provenance).
    var artifact_sha: ?[32]u8 = null;
    if (cli.artifact) |p| {
        artifact_sha = sha256File(io, p, gpa) catch |e| blk: {
            std.debug.print("warn: could not hash artifact '{s}': {s} (sidecar will record null)\n", .{ p, @errorName(e) });
            break :blk null;
        };
    }

    const out_dir = std.fs.path.dirname(cli.out_path) orelse "";
    if (out_dir.len > 0) {
        std.Io.Dir.cwd().createDirPath(io, out_dir) catch {};
    }

    const cwd = std.Io.Dir.cwd();

    if (dims.w == 2 and dims.h == 2) {
        try runExhaustive(2, 2, io, gpa, cwd, cli, artifact_sha);
    } else if (dims.w == 3 and dims.h == 2) {
        try runExhaustive(3, 2, io, gpa, cwd, cli, artifact_sha);
    } else if (dims.w == 3 and dims.h == 3) {
        try runExhaustive(3, 3, io, gpa, cwd, cli, artifact_sha);
    } else if (dims.w == 4 and dims.h == 4) {
        const n_total: u32 = cli.sample orelse 50000;
        try runSampled(4, 4, io, gpa, cwd, cli, artifact_sha, n_total);
    } else {
        usageMsg();
        std.debug.print("error: unsupported goban {d}x{d} (2x2, 3x2, 3x3, 4x4)\n", .{ dims.w, dims.h });
        std.process.exit(2);
    }
}

fn runVerify(io: std.Io, gpa: std.mem.Allocator, in_path: []const u8, w: usize, h: usize) !void {
    const cwd = std.Io.Dir.cwd();
    const bytes = cwd.readFileAlloc(io, in_path, gpa, .unlimited) catch |e| {
        std.debug.print("VERDICT: FATAL — cannot read '{s}': {s}\n", .{ in_path, @errorName(e) });
        std.process.exit(1);
    };
    defer gpa.free(bytes);
    const v = validate(bytes, w, h) catch |e| {
        std.debug.print("VERDICT: FAIL — '{s}' invalid: {s}\n", .{ in_path, @errorName(e) });
        std.process.exit(1);
    };
    std.debug.print("VERDICT: OK — '{s}' {d}x{d} records={d} colex_bytes={d} moves_bytes={d} slice=ko{d}/passes{d}\n", .{ in_path, w, h, v.record_count, v.cb, v.mb, SLICE_KO_NONE, SLICE_PASSES });
}

fn writeOut(io: std.Io, cwd: std.Io.Dir, path: []const u8, bytes: []const u8) !void {
    var file = try cwd.createFile(io, path, .{});
    defer file.close(io);
    try file.writePositionalAll(io, bytes, 0);
}

fn runExhaustive(
    comptime w: usize,
    comptime h: usize,
    io: std.Io,
    gpa: std.mem.Allocator,
    cwd: std.Io.Dir,
    cli: Cli,
    artifact_sha: ?[32]u8,
) !void {
    const t0 = nowMs();
    const res = try emitExhaustive(w, h, gpa);
    defer gpa.free(res.file);
    _ = validate(res.file, w, h) catch |e| {
        std.debug.print("FATAL: self-validation failed for {d}x{d}: {s}\n", .{ w, h, @errorName(e) });
        std.process.exit(1);
    };
    try writeOut(io, cwd, cli.out_path, res.file);
    // Sidecar.
    const sidecar = try buildExhaustiveSidecar(gpa, w, h, colexBytes(w * h), rules.Rules(w, h).moves_bytes, res.record_count, res.legal_count, cli.artifact, artifact_sha);
    defer gpa.free(sidecar);
    const sidecar_path = try std.fmt.allocPrint(gpa, "{s}.json", .{cli.out_path});
    defer gpa.free(sidecar_path);
    try writeOut(io, cwd, sidecar_path, sidecar);
    const dt = nowMs() - t0;
    std.debug.print("smd1 {d}x{d} exhaustive: {d} records ({d} legal positions x 2 sides) -> {s} ({d} bytes, {d} ms)\n", .{ w, h, res.record_count, res.legal_count, cli.out_path, res.file.len, dt });
    std.debug.print("smd1 sidecar -> {s}\n", .{sidecar_path});
}

fn runSampled(
    comptime w: usize,
    comptime h: usize,
    io: std.Io,
    gpa: std.mem.Allocator,
    cwd: std.Io.Dir,
    cli: Cli,
    artifact_sha: ?[32]u8,
    n_total: u32,
) !void {
    const t0 = nowMs();
    const res = try emitSampled(w, h, gpa, cli.seed, n_total, cli.artifact, artifact_sha);
    defer gpa.free(res.file);
    defer gpa.free(res.sidecar);
    _ = validate(res.file, w, h) catch |e| {
        std.debug.print("FATAL: self-validation failed for {d}x{d}: {s}\n", .{ w, h, @errorName(e) });
        std.process.exit(1);
    };
    try writeOut(io, cwd, cli.out_path, res.file);
    const sidecar_path = try std.fmt.allocPrint(gpa, "{s}.json", .{cli.out_path});
    defer gpa.free(sidecar_path);
    try writeOut(io, cwd, sidecar_path, res.sidecar);
    const dt = nowMs() - t0;
    std.debug.print("smd1 {d}x{d} sampled: {d} records (seed={d}, {d} strata x {d}/side) -> {s} ({d} bytes, {d} ms)\n", .{ w, h, res.record_count, cli.seed, 10, n_total / 20, cli.out_path, res.file.len, dt });
    std.debug.print("smd1 sidecar -> {s}\n", .{sidecar_path});
}

// ── tests ──────────────────────────────────────────────────────────────────
//
// Run standalone (before build.zig wiring):
//   zig test --dep rules --dep colex --dep enumerate \
//       -Mmain=tools/smd1.zig -Mrules=src/rules.zig -Mcolex=src/colex.zig \
//       -Menumerate=src/enumerate.zig

const testing = std.testing;

test "colexBytes per goban (design-M1 §4.6.2)" {
    try testing.expectEqual(@as(u8, 1), colexBytes(4)); // 2x2
    try testing.expectEqual(@as(u8, 4), colexBytes(6)); // 3x2
    try testing.expectEqual(@as(u8, 4), colexBytes(9)); // 3x3
    try testing.expectEqual(@as(u8, 4), colexBytes(12)); // 4x3
    try testing.expectEqual(@as(u8, 8), colexBytes(16)); // 4x4
}

test "2x2 exhaustive: 57 legal positions -> 114 records, CRC validates" {
    const gpa = testing.allocator;
    const res = try emitExhaustive(2, 2, gpa);
    defer gpa.free(res.file);
    // OEIS A094777 (square) gives 2x2 = 57 legal positions.
    try testing.expectEqual(@as(u32, 57), res.legal_count);
    try testing.expectEqual(@as(u32, 114), res.record_count);
    const v = try validate(res.file, 2, 2);
    try testing.expectEqual(@as(u32, 114), v.record_count);
    try testing.expectEqual(@as(u8, 1), v.cb); // colex_bytes
    try testing.expectEqual(@as(u8, 1), v.mb); // moves_bytes = ceil(5/8)
}

test "2x2 empty-board record: all 4 cells + pass legal (bitmap 0x1F)" {
    const gpa = testing.allocator;
    const res = try emitExhaustive(2, 2, gpa);
    defer gpa.free(res.file);
    // Record 0 is (colex=0, Black): empty board, ko=NONE, passes=0.
    // colex_bytes=1, so record layout = [colex(1), side(1), bitmap(1)].
    const r0 = res.file[HEADER_LEN..][0..3];
    try testing.expectEqual(@as(u8, 0), r0[0]); // colex 0
    try testing.expectEqual(@as(u8, 1), r0[1]); // Black
    // bits 0..3 = the 4 cells (all legal on the empty board), bit 4 = pass.
    try testing.expectEqual(@as(u8, 0x1F), r0[2]);
    // Record 1 is (colex=0, White): same bitmap (empty board is symmetric).
    const r1 = res.file[HEADER_LEN..][3..6];
    try testing.expectEqual(@as(u8, 0), r1[0]);
    try testing.expectEqual(@as(u8, 2), r1[1]); // White
    try testing.expectEqual(@as(u8, 0x1F), r1[2]);
}

test "2x2 records sorted by (colex, side) ascending" {
    const gpa = testing.allocator;
    const res = try emitExhaustive(2, 2, gpa);
    defer gpa.free(res.file);
    const cb: usize = 1;
    const mb: usize = 1;
    const rec_size = cb + 1 + mb;
    var i: usize = 0;
    var prev_colex: u64 = 0;
    var prev_side: u8 = 0;
    while (i < res.record_count) : (i += 1) {
        const off = HEADER_LEN + i * rec_size;
        const colex_val: u64 = res.file[off];
        const side = res.file[off + cb];
        if (i > 0) {
            if (colex_val == prev_colex) {
                try testing.expect(side >= prev_side);
            } else {
                try testing.expect(colex_val > prev_colex);
            }
        }
        prev_colex = colex_val;
        prev_side = side;
    }
}

test "CRC-32 catches a corrupted record byte" {
    const gpa = testing.allocator;
    const res = try emitExhaustive(2, 2, gpa);
    defer gpa.free(res.file);
    var bad = try gpa.dupe(u8, res.file);
    defer gpa.free(bad);
    // Flip a bit in the first record (just past the header).
    bad[HEADER_LEN] ^= 0x01;
    try testing.expectError(error.BadCrc, validate(bad, 2, 2));
}

test "bad magic / version / slice are rejected" {
    const gpa = testing.allocator;
    const res = try emitExhaustive(2, 2, gpa);
    defer gpa.free(res.file);
    var bad = try gpa.dupe(u8, res.file);
    defer gpa.free(bad);
    bad[0] = 'X'; // bad magic
    try testing.expectError(error.BadMagic, validate(bad, 2, 2));

    var bad2 = try gpa.dupe(u8, res.file);
    defer gpa.free(bad2);
    bad2[4] = 99; // bad version
    try testing.expectError(error.BadVersion, validate(bad2, 2, 2));

    var bad3 = try gpa.dupe(u8, res.file);
    defer gpa.free(bad3);
    bad3[16] = 0; // slice_ko != 255
    try testing.expectError(error.BadSlice, validate(bad3, 2, 2));
}

test "3x2 exhaustive: 489 legal positions -> 978 records, validates" {
    const gpa = testing.allocator;
    const res = try emitExhaustive(3, 2, gpa);
    defer gpa.free(res.file);
    // 3x2 legal-position count = 489 (docs/research/retrograde-4x4.md table).
    try testing.expectEqual(@as(u32, 489), res.legal_count);
    try testing.expectEqual(@as(u32, 978), res.record_count);
    const v = try validate(res.file, 3, 2);
    try testing.expectEqual(@as(u32, 978), v.record_count);
    try testing.expectEqual(@as(u8, 4), v.cb); // colex_bytes
    try testing.expectEqual(@as(u8, 1), v.mb); // moves_bytes = ceil(7/8) = 1
}

test "3x3 exhaustive: 12675 legal positions -> 25350 records, validates" {
    const gpa = testing.allocator;
    const res = try emitExhaustive(3, 3, gpa);
    defer gpa.free(res.file);
    // OEIS A094777: 3x3 = 12,675 legal positions.
    try testing.expectEqual(@as(u32, 12675), res.legal_count);
    try testing.expectEqual(@as(u32, 25350), res.record_count);
    const v = try validate(res.file, 3, 3);
    try testing.expectEqual(@as(u32, 25350), v.record_count);
    try testing.expectEqual(@as(u8, 4), v.cb); // colex_bytes
    try testing.expectEqual(@as(u8, 2), v.mb); // moves_bytes = ceil(10/8) = 2
}

test "4x4 sampled: 200 states (10 strata x 10), seed 31337, validates + sidecar" {
    // Small N keeps the test fast; 200 = 10 strata x 10 = 5 per stratum-side.
    const gpa = testing.allocator;
    const res = try emitSampled(4, 4, gpa, 31337, 200, null, null);
    defer gpa.free(res.file);
    defer gpa.free(res.sidecar);
    try testing.expectEqual(@as(u32, 200), res.record_count);
    // N=200 -> n_per_stratum_side = 200/20 = 10; 10 strata x 10/side = 200,
    // split 100 Black / 100 White.
    var black: u32 = 0;
    var white: u32 = 0;
    for (res.strata) |s| {
        black += s.black;
        white += s.white;
        try testing.expectEqual(@as(u32, 10), s.black);
        try testing.expectEqual(@as(u32, 10), s.white);
    }
    try testing.expectEqual(@as(u32, 100), black);
    try testing.expectEqual(@as(u32, 100), white);
    const v = try validate(res.file, 4, 4);
    try testing.expectEqual(@as(u32, 200), v.record_count);
    try testing.expectEqual(@as(u8, 8), v.cb); // colex_bytes
    try testing.expectEqual(@as(u8, 3), v.mb); // moves_bytes = ceil(17/8) = 3
    // Sidecar carries the seed and strata counts (brief acceptance #4).
    try testing.expect(std.mem.indexOf(u8, res.sidecar, "\"seed\": 31337") != null);
    try testing.expect(std.mem.indexOf(u8, res.sidecar, "\"sample_size\": 200") != null);
    try testing.expect(std.mem.indexOf(u8, res.sidecar, "\"strata\":") != null);
}

test "4x4 sampled records are sorted by (colex, side) and unique" {
    const gpa = testing.allocator;
    const res = try emitSampled(4, 4, gpa, 31337, 200, null, null);
    defer gpa.free(res.file);
    defer gpa.free(res.sidecar);
    const cb: usize = 8;
    const mb: usize = 3;
    const rec_size = cb + 1 + mb;
    var i: usize = 0;
    var prev_key: u64 = 0;
    var prev_side: u8 = 0;
    while (i < res.record_count) : (i += 1) {
        const off = HEADER_LEN + i * rec_size;
        var colex_val: u64 = 0;
        for (0..cb) |b| colex_val |= @as(u64, res.file[off + b]) << @intCast(b * 8);
        const side = res.file[off + cb];
        if (i > 0) {
            if (colex_val == prev_key) {
                try testing.expect(side >= prev_side);
            } else {
                try testing.expect(colex_val > prev_key);
            }
        }
        prev_key = colex_val;
        prev_side = side;
    }
}

test "round-trip: a sampled 4x4 record's bitmap matches a direct kernel call" {
    // Pick the first record, reconstruct the position from its colex, re-run
    // the kernel move generator at ko=NONE/passes=0, and compare bitmaps.
    const gpa = testing.allocator;
    const res = try emitSampled(4, 4, gpa, 31337, 200, null, null);
    defer gpa.free(res.file);
    defer gpa.free(res.sidecar);
    const R = rules.Rules(4, 4);
    const X = colex.Indexer(4, 4);
    const cb: usize = 8;
    const mb: usize = 3;
    const off = HEADER_LEN;
    var colex_idx: u64 = 0;
    for (0..cb) |b| colex_idx |= @as(u64, res.file[off + b]) << @intCast(b * 8);
    const side_byte = res.file[off + cb];
    const side: i8 = if (side_byte == 1) 1 else -1;
    const pos = X.pos_from_colex(colex_idx);
    const bm = R.legalMoves(&pos, side, R.ko_none(), 0);
    try testing.expectEqualSlices(u8, bm[0..], res.file[off + cb + 1 ..][0..mb]);
}